django_ensyu1/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('article/list/', views.ArticleListView.as_view(), name='article_list'),
    path('article/detail/<int:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
    path('tag/list/', views.TagListView.as_view(), name='tag_list'),
    path('tag/create/', views.TagCreateView.as_view(), name='tag_create'),
    path('article/create/', views.ArticleCreateView.as_view(), name='article_create'),
    path('article_update/<int:pk>/', views.ArticleUpdate.as_view(), name='article_update'),
    path('article_delete/<int:pk>/',views.ArticleDelete.as_view(), name='article_delete'),
    path('comment/create/<int:pk>',views.CommentCreateView.as_view(), name='comment_create'),
]

django_ensyu1/conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

django_ensyu1/blog/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=255)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField('タグ名', max_length=255)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField('タイトル', max_length=255)
    text = models.TextField('本文')
    created_at = models.DateTimeField('作成日', default=timezone.now)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='カテゴリ')

    # タグは複数紐づく。また、タグを設定しないことも可能にしている(blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True, null=True, verbose_name='タグ')

    def __str__(self):
        return self.title


class Comment(models.Model):
    name = models.CharField('名前', default='名無し',max_length=100)
    text = models.TextField('コメント内容')
    target = models.ForeignKey(
        Article, on_delete=models.SET_NULL,
        blank=True, null=True,
        verbose_name='紐づく記事'
    )

    def __str__(self):
        return self.text[:15]
# Create your models here.

django_ensyu1/blog/forms.py
from django import forms

from .models import Tag, Article,Comment


class TagCreateForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ('name',)


class ArticleCreateForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'text', 'created_at', 'category', 'tags',)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'text')

class ArticleUpdateForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'text', 'created_at', 'category', 'tags',)

class SearchForm(forms.Form):
    keyword = forms.CharField(label='キーワード', required=False)

django_ensyu1/blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import redirect
from .forms import TagCreateForm, ArticleCreateForm,ArticleUpdateForm,SearchForm,CommentCreateForm
from .models import Article, Tag,Comment


class Home(generic.TemplateView):
    template_name = 'blog/home.html'


class ArticleListView(generic.ListView):
    model = Article
    template_name = 'blog/article_list.html'
    queryset = Article.objects.all().order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # フォーム(request.GETやrequest.POST)とすると、
        # このフォームをテンプレートで表示すると、入力済みになっている
        context['form'] = SearchForm(self.request.GET)
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        form = SearchForm(self.request.GET)
        form.is_valid()
        keyword = form.cleaned_data.get('keyword')
        if keyword:
            #記事タイトルか本文のどちらかにキーワードが含まれていれば表示
            queryset = queryset.filter(Q(title__icontains=keyword) | Q(text__icontains=keyword))
        return queryset

class ArticleDetailView(generic.DetailView):
    model = Article
    template_name = 'blog/article_detail.html'

    def get_object(self, queryset=None):
        # self.kwargsは、URL内の int:pkといった部分が入っている
        article = Article.objects.get(pk=self.kwargs['pk'])
        # →Staff.objects.get(pk=1)  # 今回、URLは/staff_detail/1/
        # →Staff.objects.get(id=1)  # pkというのは、primarykeyのこと。今回ならidフィールドのこと
        return article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = self.get_object()
        context['tags'] = article.tags.all()
        return context


class TagListView(generic.ListView):
    model = Tag
    template_name = 'blog/tag_list.html'


# class TagListView(generic.ListView):
#     model = Article
#     template_name = 'blog/tag_list.html'
# Create your views here.

class TagCreateView(generic.CreateView):
    model = Tag
    template_name = 'blog/tag_create.html'
    success_url = reverse_lazy('blog:article_list')
    form_class = TagCreateForm


class ArticleCreateView(generic.CreateView):
    model = Article
    template_name = 'blog/article_create.html'
    success_url = reverse_lazy('blog:article_list')
    form_class = ArticleCreateForm


class ArticleUpdate(generic.UpdateView):
    model = Article
    form_class = ArticleUpdateForm
    template_name = 'blog/article_update.html'
    success_url = reverse_lazy('blog:article_list')

class ArticleDelete(generic.DeleteView):
    model = Article
    template_name = 'blog/article_delete.html'
    success_url = reverse_lazy('blog:article_list')

class CommentCreateView(generic.CreateView):
    model = Comment
    template_name = 'blog/comment_create.html'
    success_url = reverse_lazy('blog:article_list')
    form_class = CommentCreateForm

    def form_valid(self, form):
        # form.save(commit=False) データベースにはまだ保存しない
        # commit=Falseビューで、モデルのフィールドを埋めるために使う引数
        comment = form.save(commit=False)

        # Commentモデルの、targetフィールドをここで埋める
        # モデル名.objects.get(フィールド=値)  1つだけ、DBから取り出すのに使うのがget
        # url内の<int:pk>は、self.kwargs['pk'] で取得できる
        comment.target = Article.objects.get(pk=self.kwargs['pk'])

        comment.save()  # saveしないと保存されない
        return redirect('blog:article_list')

django_ensyu1/templates/base.html
<!DOCTYPE html>
  {% load static %}
  <html lang="ja">
  <head>
      <link rel="stylesheet" href="{% static 'css/basic.css' %}">
      <title>{% block title %}Python 講座{% endblock %}</title>
  </head>
  <body>
      <p><a href={% url 'blog:article_list' %}>article_listへ</a></p>
      <div id="content">
        {% block content %}{% endblock %}
      </div>
  </body>
  </html>

django_ensyu1/templates/blog/article_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">送信</button>
</form>

{% endblock %}
</body>
</html>

django_ensyu1/templates/blog/article_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <p>"{{ article.title }}"を削除してもよろしいですか?</p>
  <input type="submit" value="削除">
</form>

{% endblock %}
</body>
</html>

django_ensyu1/templates/blog/article_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% extends 'base.html' %}

{% block content %}

<h1>記事詳細ページ</h1>
<p>記事のタイトル {{ article.title }}</p>
<p>本文 {{ article.text }}</p>
<p>作成日 {{ article.created_at }}</p>
<p>タグ

<!--コンテキスト使わないで表示したやつ-->
    {% for tag in article.tags.all %}
        {{ tag.name }}
    {% endfor %}

<!--コンテキストで表示したやつ-->
    {% for tag in tags %}
        {{ tag.name }}
    {% endfor %}

</p>
<p>カテゴリ {{ article.category.name }}</p>
<h1>コメント欄</h1>
{% for comment in article.comment_set.all %}
<div>
    {{ comment.name }}
    {{ comment.text }}
</div>
{% endfor %}
<a href="{% url 'blog:comment_create' article.pk %}">コメント作成</a>
{% endblock %}
</body>
</html>

django_ensyu1/templates/blog/article_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% extends 'base.html' %}
{% block content %}

<form action ="" method=""GET>
    {{ form.as_div }}
    <button type="submit">検索</button>
</form>

<!--for articleのarticleが下のarticle.tags.allのarticleと対応してる-->
{% for article in article_list %}
    <a href="{% url 'blog:article_detail' article.pk %}">{{ article.title }}</a> / {{ article.created_at }}
<!--コンテキスト使わないで表示-->
{% for tag in article.tags.all %}
    {{ tag.name }}
{% endfor %}

<a href="{% url 'blog:article_update' article.pk %}">更新</a>
<a href="{% url 'blog:article_delete' article.pk %}">削除</a>
<a href="{% url 'blog:comment_create' article.pk %}">コメント作成</a>
<br>
{% endfor %}
<!--&lt;!&ndash;コンテキスト使って表示&ndash;&gt;-->
<!--{% for tag in tags %}-->
<!--{{ tag.name }}-->
<!--{% endfor %}-->
<p>
<a href="{% url 'blog:article_create' %}">article作成</a>
{% endblock %}


</body>
</html>

django_ensyu1/templates/blog/article_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}

{% block content %}
<h2>商品情報更新ページ</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" id="save" value="更新">
</form>

{% endblock %}
</body>
</html>

django_ensyu1/templates/blog/comment_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">送信</button>
</form>

{% endblock %}
</body>
</html>

django_ensyu1/templates/blog/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>TOP PAGE</h1>
</body>
</html>

django_ensyu1/templates/blog/tag_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_div }}
  <button type="submit">送信</button>
</form>

{% endblock %}
</body>
</html>

django_ensyu1/templates/blog/tag_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--{% for article in article_list %}-->
<!--{% for tag in article.tags.all %}-->
<!--    {{ tag.name }}-->
<!--{% endfor %}-->
<!--<p>-->
<!--{% endfor %}-->

{% for tag in tag_list %}
   <p>{{ tag.name }}
{% endfor %}
</body>
</html>